"""PDF report generation for ROV analysis results."""

import os
import logging
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos

from rov_app.core.constants import URGENCY_RGB
from rov_app.core.telemetry import fmt_telemetry, fmt_flags

log = logging.getLogger(__name__)

# English labels
LABELS = {
    "title": "ROV UNDERWATER ANALYSIS REPORT",
    "summary": "SUMMARY",
    "detailed": "DETAILED FINDINGS",
    "job_id": "Job ID",
    "video_file": "Video File",
    "total_frames": "Total Frames",
    "opencv_flagged": "OpenCV Flagged",
    "ai_analyzed": "AI Analyzed",
    "api_saved": "API Calls Saved",
    "high_urgency": "High Urgency",
    "medium_urgency": "Medium Urgency",
    "objects_found": "Objects Found",
    "structures_found": "Structures Found",
    "verification_banner": "[SYSTEM VERIFICATION]  {count} of {total} flagged frames sampled  --  NOT a full analysis",
    "time": "Time",
    "urgency": "Urgency",
    "confidence": "Confidence",
    "telemetry": "Telemetry",
    "cv_signals": "CV Signals",
    "objects": "Objects:",
    "detail": "  Detail:",
    "structures": "Structures:",
    "anomaly": "Anomaly:",
    "seabed": "Seabed:",
    "water": "Water:",
    "urgency_label": "Urgency:",
    "summary_label": "Summary:",
    "visibility": "Visibility",
    "clarity": "Clarity",
    "depth_est": "Depth est",
    "footer": "Generated by ROV Analyzer v5 (GUI)",
    "header_video": "Video",
    "header_model": "Model",
    "header_generated": "Generated",
    "urgency_none": "NONE",
    "urgency_low": "LOW",
    "urgency_medium": "MEDIUM",
    "urgency_high": "HIGH",
}


def safe(text):
    """Strip characters outside Latin-1 to avoid fpdf2 encoding errors."""
    if not text:
        return ""
    return str(text).encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf(job_meta, findings, output_path, model_name="",
                 include_detections=False, verification_mode=False):
    """
    Generate a professional PDF report.

    Args:
        job_meta: Job metadata dict
        findings: List of finding dicts with 'analysis', 'telemetry', 'cv_flags'
        output_path: Where to save the PDF
        model_name: AI model name for the header
        include_detections: Whether to include AI detection overlay frames
        verification_mode: Whether this is a verification run
    """
    L = LABELS

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    def sfn(style="", size=10):
        """Set font."""
        pdf.set_font("Helvetica", style, size)

    def txt(text):
        """Safe text."""
        return safe(text)

    pdf.add_page()
    PAGE_H = 297
    BOTTOM_MARGIN = 15
    CARD_MIN_H = 75

    # Header banner
    pdf.set_fill_color(15, 40, 75)
    pdf.rect(0, 0, 210, 42, "F")
    pdf.set_text_color(255, 255, 255)
    sfn("B", 18)
    pdf.set_xy(10, 7)
    pdf.cell(0, 10, txt(L["title"]), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    sfn("", 9)
    pdf.set_x(10)
    pdf.cell(0, 6,
             txt(f"{L['header_video']}: {job_meta['video_file']}  |  "
                 f"{L['header_model']}: {model_name}  |  "
                 f"{L['header_generated']}: {datetime.now().strftime('%Y-%m-%d %H:%M')}"),
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Verification banner
    if verification_mode:
        pdf.set_fill_color(200, 100, 0)
        pdf.set_text_color(255, 255, 255)
        sfn("B", 10)
        total_f = job_meta.get("flagged_count", len(findings))
        pdf.cell(0, 9,
                 txt("  " + L["verification_banner"].format(count=len(findings), total=total_f)),
                 fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_text_color(0, 0, 0)
    pdf.set_y(50)

    # Summary table
    total_a = len(findings)
    high_u = sum(1 for f in findings if f.get("analysis", {}).get("urgency") == "high")
    med_u = sum(1 for f in findings if f.get("analysis", {}).get("urgency") == "medium")
    all_obj = sorted({str(o) for f in findings
                      for o in f.get("analysis", {}).get("objects", {}).get("list", [])
                      if not isinstance(o, dict)})
    all_str = sorted({str(s) for f in findings
                      for s in f.get("analysis", {}).get("structures", {}).get("list", [])
                      if not isinstance(s, dict)})
    savings = job_meta["total_frames"] - len(findings)

    sfn("B", 11)
    pdf.cell(0, 7, txt(L["summary"]), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    LABEL_W = 60
    VALUE_W = 130

    def truncate(text, max_chars=90):
        s = txt(text)
        return s if len(s) <= max_chars else s[:max_chars].rstrip(", ") + "..."

    def irow(label, val, alt=False):
        pdf.set_fill_color(238, 244, 255) if alt else pdf.set_fill_color(255, 255, 255)
        row_y = pdf.get_y()
        sfn("B", 9)
        pdf.set_xy(pdf.l_margin, row_y)
        pdf.cell(LABEL_W, 6, txt(f"  {label}"), border=1, fill=True)
        sfn("", 9)
        pdf.set_xy(pdf.l_margin + LABEL_W, row_y)
        pdf.cell(VALUE_W, 6, txt(f"  {truncate(val)}"), border=1, fill=False,
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    irow(L["job_id"], job_meta["job_id"], True)
    irow(L["video_file"], job_meta["video_file"], False)
    irow(L["total_frames"], str(job_meta["total_frames"]), True)
    irow(L["opencv_flagged"], str(job_meta["flagged_count"]), False)
    irow(L["ai_analyzed"], str(total_a), True)
    irow(L["api_saved"], str(savings), False)
    irow(L["high_urgency"], str(high_u), True)
    irow(L["medium_urgency"], str(med_u), False)
    if all_obj:
        irow(L["objects_found"], ", ".join(all_obj), True)
    if all_str:
        irow(L["structures_found"], ", ".join(all_str), False)

    pdf.ln(5)

    # Detailed findings
    sfn("B", 11)
    pdf.cell(0, 7, txt(L["detailed"]), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    for idx, item in enumerate(findings):
        a = item.get("analysis") or {}
        telem = item.get("telemetry", {})
        flags = item.get("cv_flags", {})
        urgency = a.get("urgency", "none")
        r, g, b = URGENCY_RGB.get(urgency, (70, 70, 70))

        sb = a.get("seabed") or {}
        sb_type = txt(sb.get("type", "N/A") if sb else "N/A")
        sb_depth = txt(sb.get("depth_estimate", "N/A") if sb else "N/A")

        if PAGE_H - BOTTOM_MARGIN - pdf.get_y() < CARD_MIN_H:
            pdf.add_page()

        # Header bar
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        sfn("B", 9)
        urgency_display = L.get(f"urgency_{urgency}", urgency.upper())
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(190, 7,
                       txt(f"  [{idx + 1}] {item['frame']}  |  "
                           f"{L['time']}: {telem.get('timestamp', 'N/A')}  |  "
                           f"{L['urgency']}: {urgency_display}  |  "
                           f"{L['confidence']}: {a.get('confidence', 0):.0%}"),
                       fill=True)
        pdf.set_text_color(0, 0, 0)

        # Telemetry row
        pdf.set_fill_color(225, 238, 255)
        sfn("", 8)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(190, 5, txt(f"  {L['telemetry']}: {fmt_telemetry(telem)}"), fill=True)

        # CV signals row
        pdf.set_fill_color(242, 242, 242)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(190, 5, txt(f"  {L['cv_signals']}: {fmt_flags(flags)}"), fill=True)

        # Disable auto page break while drawing card body
        pdf.set_auto_page_break(False)

        # Choose which frame image to embed
        if include_detections and item.get("detected_frame_path") and os.path.exists(
                item.get("detected_frame_path", "")):
            frame_img = item["detected_frame_path"]
        else:
            frame_img = item.get("frame_path")
        has_img = frame_img and os.path.exists(frame_img)
        cur_y = pdf.get_y() + 2
        text_x = 72 if has_img else 10
        text_w = 128 if has_img else 190

        if has_img:
            try:
                pdf.image(frame_img, x=10, y=cur_y, w=58)
            except Exception as ie:
                log.warning(f"Image embed failed: {ie}")

        pdf.set_xy(text_x, cur_y)

        def aline(lbl, val, col=(0, 0, 0)):
            if pdf.get_y() > PAGE_H - BOTTOM_MARGIN - 8:
                pdf.set_auto_page_break(True, margin=BOTTOM_MARGIN)
                pdf.add_page()
                pdf.set_auto_page_break(False)
            pdf.set_xy(text_x, pdf.get_y())
            sfn("B", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(26, 5, txt(lbl), new_x=XPos.RIGHT, new_y=YPos.TOP)
            sfn("", 8)
            pdf.set_text_color(*col)
            pdf.multi_cell(text_w - 26, 5, txt(str(val)))
            pdf.set_text_color(0, 0, 0)

        # Objects
        obj_data = a.get("objects") or {}
        if obj_data.get("detected"):
            obj_items = [str(o) for o in obj_data.get("list", []) if not isinstance(o, dict)]
            aline(L["objects"], ", ".join(obj_items), (0, 80, 160))
            if obj_data.get("details"):
                aline(L["detail"], obj_data["details"])

        # Structures
        str_data = a.get("structures") or {}
        if str_data.get("detected"):
            str_items = [str(s) for s in str_data.get("list", []) if not isinstance(s, dict)]
            aline(L["structures"], ", ".join(str_items), (100, 0, 130))
            if str_data.get("details"):
                aline(L["detail"], str_data["details"])

        # Anomaly
        ano_data = a.get("anomalies") or {}
        if ano_data.get("detected"):
            aline(L["anomaly"], ano_data.get("description", ""), (170, 60, 0))

        # Seabed, water, urgency
        aline(L["seabed"], f"{sb_type}  |  {L['depth_est']}: {sb_depth}")
        aline(L["water"], f"{L['visibility']}: {txt(a.get('visibility', 'N/A'))}  |  "
                          f"{L['clarity']}: {txt(a.get('water_clarity', 'N/A'))}")
        if a.get("urgency_reason"):
            aline(L["urgency_label"], a.get("urgency_reason", ""))

        # Summary bar
        sum_y = max(pdf.get_y(), cur_y + 42) + 1
        if sum_y > PAGE_H - BOTTOM_MARGIN - 8:
            pdf.set_auto_page_break(True, margin=BOTTOM_MARGIN)
            pdf.add_page()
            pdf.set_auto_page_break(False)
            sum_y = pdf.get_y() + 2

        pdf.set_xy(10, sum_y)
        pdf.set_fill_color(255, 250, 200)
        sfn("I", 8)
        pdf.multi_cell(190, 5,
                       txt(f"  {L['summary_label']} {a.get('one_line_summary', '')}"),
                       fill=True)

        pdf.set_auto_page_break(True, margin=BOTTOM_MARGIN)
        pdf.ln(5)

    # Footer
    sfn("", 7)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5,
             txt(f"{L['footer']}  |  Model: {model_name}  |  "
                 f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"),
             align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.output(output_path)
    log.info(f"PDF saved: {output_path}")
    return output_path
